Add axis.offset
d3/d3-axis pull request #76
Opened 2021-02-21 18:55 UTC by mbostock

What do you think about making the current 0.5px offset configurable, and defaulting it to zero on devices with a devicePixelRatio ≥ 2? The purpose of this offset is to provide pixel-snapping, but that’s only necessary when the devicePixelRatio = 1, and these days, that’s uncommon.

2021-02-22 15:17 UTC, curran approved these changes
LGTM. Solid move.

2021-02-22 15:17 UTC, curran commented
Related to https://github.com/d3/d3-axis/issues/75

2021-02-23 10:31 UTC, Fil commented
I work daily on a DPI=1 desktop monitor :)

A density of 1.5 is quite common on Android phones, and it seems that it too would be better with offset = 0.

Here's the result of various settings:
https://observablehq.com/@d3/axis-offset-76

summary:


dpi | offset | result |
---|---|---
1 | 0 | bad |
1 | 0.5 | **good** |
1.5 | 0 | **good** |
1.5 | 0.5 | not so good |
2 | 0 | **good** |
2 | 0.5 | bad |



1 / 0 😡
![dpi1-offset0](https://user-images.githubusercontent.com/7001/108830386-998d9080-75c9-11eb-9ffa-120ee12067e7.png)

1 / .5 😎
![dpi1-offset0 5](https://user-images.githubusercontent.com/7001/108830291-795dd180-75c9-11eb-9f00-9f54b3f0e256.png)

1.5 / 0 😎
![dpi1 5-offset0](https://user-images.githubusercontent.com/7001/108830271-75ca4a80-75c9-11eb-9607-fd32859a095a.png)

1.5 / 1.5 😡
![dpi1 5-offset0](https://user-images.githubusercontent.com/7001/108830271-75ca4a80-75c9-11eb-9607-fd32859a095a.png)

2 / 0 😎
![dpi2-offset0](https://user-images.githubusercontent.com/7001/108830279-77940e00-75c9-11eb-96e5-f5b419d83fa6.png)

2 / .5 😡
![dpi2-offset0 5](https://user-images.githubusercontent.com/7001/108830382-97c3cd00-75c9-11eb-9517-e6485704830a.png)



(note that I used  "download png", not screen grab :))

2021-02-23 19:53 UTC, Fil requested changes
just this change for 1.5

2021-02-23 19:53 UTC, Fil commented on src/axis.js
> +      offset = typeof window !== "undefined" && window.devicePixelRatio >= 2 ? 0 : 0.5,
```suggestion
      offset = typeof window !== "undefined" && window.devicePixelRatio > 1 ? 0 : 0.5,
```

2021-02-25 10:27 UTC, Fil approved these changes

2021-03-10 19:50 UTC, merged